version: "3.3"

services:
    frontend:
        image: node:10-alpine
        volumes:
            - .:/devel
        working_dir: /devel/packages/frontend
        command: yarn start
        restart: always
        environment:
            - NODE_ENV=development
            - REACT_APP_BACKEND_URL=http://${REACT_APP_BACKEND_URL:-localhost}:${BACKEND_PORT:-1337}
        networks:
            - magnit
        depends_on:
            - backend
        ports:
            - ${FRONTEND_PORT:-3100}:3000

    backend:
        image: node:10-alpine
        volumes:
            - .:/devel
        working_dir: /devel/packages/backend
        command: npm run start:dev
        environment:
            - AIRWATCH_AUTH=${AIRWATCH_AUTH}
            - AIRWATCH_BASE_URL=${AIRWATCH_BASE_URL}
            - AIRWATCH_TENANT_CODE=${AIRWATCH_TENANT_CODE}
            - AUTH_EXPIRES_IN=${AUTH_EXPIRES_IN:-1h}
            - AUTH_SECRET=${AUTH_SECRET}
            - NODE_ENV=development
            - BACKEND_PORT=${BACKEND_PORT:-1337}
            - BACKEND_HOST=${BACKEND_HOST:-http://localhost:1337}
            - POSTGRES_PORT=${POSTGRES_PORT:-5432}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-magnit}
            - POSTGRES_USER=${POSTGRES_USER:-magnit}
            - POSTGRES_HOST=${POSTGRES_HOST:-db}
            - POSTGRES_DB=${POSTGRES_DB:-magnit}
            - RABBITMQ_HOST=${RABBITMQ_HOST:-amqp}
            - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
            - RABBITMQ_USER=${RABBITMQ_USER:-magnit}
            - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-magnit}
            - SMTP_FROM=${MAIL_FROM:-'"Магнит" <magnit@mail.com>'}
            - SMTP_HOST=${SMTP_HOST:-smtp.mailtrap.io}
            - SMTP_PORT=${SMTP_PORT:-2525}
            - SMTP_USER=${SMTP_USER}
            - SMTP_PASS=${SMTP_PASS}
            - ALLOW_AUTH=${ALLOW_AUTH}
            - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
            - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
            - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
            - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
            - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
            - FIREBASE_CLIENT_X509_CERT_URL=${FIREBASE_CLIENT_X509_CERT_URL}
            - ADMIN_ROLE_DESCRIPTION=${ADMIN_ROLE_DESCRIPTION}
            - ADMIN_ROLE_TITLE=${ADMIN_ROLE_TITLE}
            - ADMIN_ROLE_ID=${ADMIN_ROLE_ID}
        restart: always
        networks:
            - magnit
        ports:
            - ${BACKEND_PORT:-1337}:${BACKEND_PORT:-1337}
        depends_on:
            - amqp
            - db

    amqp:
        image: rabbitmq:3.7-alpine
        restart: always
        ports:
            - ${RABBITMQ_PORT:-5672}:${RABBITMQ_PORT:-5672}
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-magnit}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-magnit}
        networks:
            - magnit
        volumes:
            - amqp:/var/lib/rabbitmq/mnesia

    db:
        image: postgres:11-alpine
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-magnit}
            - POSTGRES_DB=${POSTGRES_DB:-magnit}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-magnit}
        networks:
            - magnit
        ports:
            - ${POSTGRES_PORT:-5432}:5432
        volumes:
            - db:/var/lib/postgresql/data

volumes:
    amqp:
        external:
            name: magnit-amqp
    db:
        external:
            name: magnit-db

networks:
    magnit:
